### PR TITLE
v3.1.0

### LINKED ISSUE #96: TypeError: Cannot read property 'append' of undefined after upgrading to 3.0.0
I am using the `jest-html-reporter` to parse results of unit tests on that I run using command
```
CI=true react-scripts test  --silent --coverage --noStackTrace --ci --json --testResultsProcessor=./node_modules/jest-html-reporter --outputFile=./coverage/test-results.json"
```
It worked fine when I was using version `2.7.0`, when I upgraded to `3.0.0` I started getting such an error
```
TypeError: Cannot read property 'append' of undefined
    at h.setupConfig (/Users/mdrzazga/Work/mstrio_ui/production/node_modules/jest-html-reporter/dist/index.js:1:6242)
    at new h (/Users/mdrzazga/Work/mstrio_ui/production/node_modules/jest-html-reporter/dist/index.js:1:1341)
    at f (/Users/mdrzazga/Work/mstrio_ui/production/node_modules/jest-html-reporter/dist/index.js:1:8783)
    at module.exports (/Users/mdrzazga/Work/mstrio_ui/production/node_modules/jest-html-reporter/dist/index.js:1:8911)
    at processResults (/Users/mdrzazga/Work/mstrio_ui/production/node_modules/@jest/core/build/runJest.js:242:47)
    at /Users/mdrzazga/Work/mstrio_ui/production/node_modules/@jest/core/build/runJest.js:429:14
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/mdrzazga/Work/mstrio_ui/production/node_modules/@jest/core/build/runJest.js:148:24)
    at _next (/Users/mdrzazga/Work/mstrio_ui/production/node_modules/@jest/core/build/runJest.js:168:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error Command failed with exit code 1.
```
When I reverted back to `2.7.0` it was working again.
My `package.json`:
```json
{
  "name": "project",
  "version": "0.0.1",
  "private": true,
  "homepage": ".",
  "dependencies": {
    "antd": "3.19.1",
    "axios": "0.19.2",
    "i18next": "19.3.4",
    "line-clamp": "1.0.0",
    "moment": "2.24.0",
    "node-sass": "4.13.1",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-i18next": "11.3.4",
    "react-scripts": "3.4.1",
    "set-value": "3.0.1",
    "tabbable": "4.0.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "serve": "serve -s build",
    "test": "react-scripts test --env=jsdom",
    "test:all": "react-scripts test --env=jsdom --watchAll=false",
    "test:ci": "CI=true react-scripts test  --silent --noStackTrace --ci",
    "test:ci_report": "CI=true react-scripts test  --silent --coverage --noStackTrace --ci --json --testResultsProcessor=./node_modules/jest-html-reporter --outputFile=./coverage/test-results.json",
    "coverage": "react-scripts test --env=jsdom --coverage",
    "coverage:all": "react-scripts test --env=jsdom --coverage --watchAll=false",
    "eject": "react-scripts eject",
    "storybook": "start-storybook -p 9009 -s public",
    "storybook:build": "build-storybook -s public",
    "eslint": "eslint ./src --ext .js,.jsx",
    "eslint:report": "eslint ./src --ext .js,.jsx -f html -o ./eslint/index.html"
  },
  "devDependencies": {
    "@storybook/addon-knobs": "5.3.18",
    "@storybook/preset-create-react-app": "2.1.1",
    "@storybook/react": "5.3.18",
    "@storybook/theming": "5.3.18",
    "enzyme": "3.11.0",
    "enzyme-adapter-react-16": "1.15.2",
    "eslint": "6.8.0",
    "eslint-config-airbnb": "18.1.0",
    "eslint-plugin-import": "2.20.2",
    "eslint-plugin-jest": "23.8.2",
    "eslint-plugin-jsx-a11y": "6.2.3",
    "eslint-plugin-react": "7.19.0",
    "eslint-plugin-react-hooks": "3.0.0",
    "jest-html-reporter": "3.0.0",
    "prop-types": "15.7.2",
    "regenerator-runtime": "0.13.5"
  },
  "jest": {
    "collectCoverageFrom": [
      "src/utilities/**/*.{js,jsx}",
      "src/components/**/*.{js,jsx}",
      "!src/components/**/*.stories.{js,jsx}"
    ],
    "transformIgnorePatterns": [
      "/node_modules/(?!(react-dnd))/"
    ]
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie < 11",
    "not op_mini all"
  ]
}
```

### LINKED ISSUE #98: `ouputPath` does not use `<rootDir>` token anymore - 3.x
Hi,

in version 2.x the Jest `<rootDir>` token was properly used and converted when used in config.
Starting from 3.x is not the case anymore and I don't see anything related in the changelog, regression?

```js
{
  pageTitle: 'Hello',
  outputPath: '<rootDir>/reports/index.html',
},
```

### PR DESCRIPTION
**Pull request by Hargne**
### Features & Fixes:
- Fixed crash when running without any configuration options
*Fixes #96*
- Added back replacing Jest's own `<rootDir>` to the actual root directory
*Fixes #98*
- Added and rewrote `append` method to append the report HTML inside the body tag of the provided file.

### CODE REVIEW

File: src/htmlreporter.ts [hunk 1]
```diff
@@ -32,11 +32,13 @@ class HTMLReporter {
   public async generate() {
     try {
       const report = await this.renderTestReport();
-      const outputPath = this.getConfigValue("outputPath") as string;
+      let outputPath = this.getConfigValue("outputPath") as string;
+      // Replace <rootDir> with the actual path to root
+      outputPath = outputPath.replace(/<rootdir>/gi, ".");
```
Comment (pascalduez) [inline src/htmlreporter.ts:37]: I'm afraid it is a tad more complicated ;) 
For instance if you set the jest `rootDir` config option to something else than the project root.  

See https://github.com/jest-community/jest-junit/blob/master/utils/replaceRootDirInPath.js

Comment (Hargne) [reply src/htmlreporter.ts:37]: I agree that this should be the case. 
However this would be considered a new feature, as the 2.x way of handling this was a simple rewrite (and tbf the request was to restore that functionality). 

With that said though, I will research the matter a bit more and update the PR

**Comment by Hargne** [comment]
@pascalduez please have a look at the latest commit 🙏

**Comment by pascalduez** [comment]
>@pascalduez please have a look at the latest commit

Looking really good! 
Thank you very much @Hargne <3
